apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-k8s-deployment
  labels:
    app: webapi-k8s
spec:
  replicas: 6
  selector:
    matchLabels:
        app: webapi-k8s
  template:
    metadata:
      labels:
        app: webapi-k8s
    spec:
      containers:
      - name: webapi-k8s-main
        image: carlsoncoder/webapi-k8s:v1
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 80